server:
  port: 80


eureka:
  client:
    #向注册中心注册自己
    register-with-eureka: true
    #表示是服务
    fetch-registry: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka
  instance:
    instance-id: consumer80   #隐藏主机名
    prefer-ip-address: true   #hover路径可以显示IP地址
spring:
  application:
    name: cloud-order-service
  zipkin:
    base-url: http://127.0.0.1:9411
  sleuth:
    sampler:
      probability: 1