server:
  port: 9527

spring:
  application:
    name: cloud-gateway
  cloud:
    gateway:
      routes:
        - id: payment_routh
          uri: lb://cloud-payment-service
          predicates:
            - Path=/payment/get/**
            # 设置正常使用事件，这个时间之后才能用
#            - After=2020-03-27T22:04:05.866+08:00[Asia/Shanghai]
#            - Cookie=username,zzyy
#            - Header=X-Request-Id, \d+
            - Method=Get
#            - Before=2020-03-27T22:04:05.866+08:00[Asia/Shanghai]


      discovery:
        locator:
          enabled: true

eureka:
  instance:
    hostname: cloud-gateway-service
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka

